config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :itineraries
    resources :itinerary_users

    root to: "users#index"
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: [:show, :edit, :update] do
    resources :itineraries, only: [:index]
  end

  resources :itineraries, only: [:new, :create, :edit, :show, :update, :destroy]
  resources :itinerary_users
  resources :searches

  root to: "searches#new"
end

app/models/itinerary.rb
# == Schema Information
#
# Table name: itineraries
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  city           :string
#  name           :string
#  price          :decimal(10, 2)
#  description    :text
#  total_capacity :integer
#  spots_sold     :integer
#  start_time     :datetime
#  end_time       :datetime
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  pic_url        :string
#  date           :date
#

class Itinerary < ActiveRecord::Base
  belongs_to :user
  has_many :users, through: :itinerary_users
  has_many :itinerary_users, inverse_of: :itinerary, dependent: :destroy

  validate :enough_spots

  def host
    user
  end

  def guests
    users
  end

  def increase_spots_sold
    old_spots_sold = spots_sold
    update_attributes(spots_sold: old_spots_sold + 1)
  end

  def enough_spots
    errors.add(:not_enough_spots, "Trip fully booked!") if (spots_sold > total_capacity)
  end
end

app/controllers/admin/itineraries_controller.rb
module Admin
  class ItinerariesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Itinerary.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Itinerary.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  def index
    @user = User.where(id: params[:user_id]).limit(1).first
    @host_itineraries = @user.host_itineraries
    @guest_itineraries = @user.guest_itineraries
  end

  def new
    @itinerary = Itinerary.new
  end

  def create
    params[:itinerary][:spots_sold] = 0
    params[:itinerary][:user_id] = current_user.id
    @itinerary = Itinerary.create!(itinerary_params)
    redirect_to itinerary_path(@itinerary)
  end

  def edit
    @itinerary = Itinerary.find(params[:id])
  end

  def show
    itinerary_id = params["id"]
    @itinerary = Itinerary.where(id: itinerary_id).limit(1).first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @itinerary }
    end
  end

  def update
    itinerary_id = params["id"]
    @itinerary = Itinerary.where(id: itinerary_id).limit(1).first
    @itinerary.update_attributes(itinerary_params)
    redirect_to itinerary_path(@itinerary)
  end

  def destroy
  end

  def itinerary_params
    params.require(:itinerary).permit(:name, :city, :price, :description, :total_capacity, :spots_sold, :user_id, :pic_url, :date) # permit all fields you want to allow
  end
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/views/itineraries/_form.html.erb
<%= form_for @itinerary do |f| %>
  <div>
    <%= f.label(:name, "Itinerary Name") %>
    <%= f.text_field(:name) %>
  </div>

  <div>
    <%= f.label(:city, "City") %>
    <%= f.text_field(:city) %>
  </div>

  <div>
    <%= f.label(:price, "Price") %>
    <%= f.text_field(:price) %>
  </div>

  <div>
    <%= f.label(:description, "Description") %>
    <%= f.text_area :description, rows: 20, cols: 30 %>
  </div>

  <div>
    <%= f.label(:total_capacity, "Total Capacity") %>
    <%= f.text_field(:total_capacity) %>
  </div>

  <div>
    <%= f.label(:pic_url, "Pic URL") %>
    <%= f.text_field(:pic_url) %>
  </div>

  <p>
    <%= f.label :date, "Date" %>
    <%= f.date_field :date %>
  </p>

  <%= submit_tag %>
<% end %>

app/views/itineraries/_itinerary.html.erb
<p><%= itinerary.name %></p>

app/views/itineraries/create.html.erb
<p>Find me in app/views/itineraries/create.html.erb</p>

app/views/itineraries/destroy.html.erb
<p>Find me in app/views/itineraries/destroy.html.erb</p>

app/views/itineraries/edit.html.erb
<p>Find me in app/views/itineraries/edit.html.erb</p>

<%= render 'form' %>

app/views/itineraries/index.html.erb
<h1>My Itineraries</h1>
<h2> Tours I'm hosting </h2>

<%= link_to "Host new Itinerary", new_itinerary_path %>

<ul>
  <% @host_itineraries.each do |itinerary| %>
  <li> <%= link_to itinerary.name, itinerary_path(itinerary) %>  -
<%= link_to "Edit", edit_itinerary_path(itinerary) %> - (Total seats left: <%= itinerary.total_capacity - itinerary.spots_sold %> of <%= itinerary.total_capacity %>)</li>
  <% end %>
</ul>

<h2> Tours I'm going on </h2>
<ul>
  <% @guest_itineraries.each do |itinerary| %>
  <li> <%= link_to itinerary.name, itinerary_path(itinerary) %></li>
  <% end %>
</ul>

app/views/itineraries/new.html.erb
<h1>Create Itinerary</h1>

<%= render 'form' %>

app/views/itineraries/show.html.erb
<h1><%= @itinerary.name %></h1>

<p><%= @itinerary.description %></p>

People coming: <%= @itinerary.spots_sold %> (Total seats left: <%= @itinerary.total_capacity - @itinerary.spots_sold %> of <%= @itinerary.total_capacity %>)
<ul>
  <% @itinerary.guests.each do |guest| %>
  <li><%= guest.full_name %></li>
  <% end %>
</ul>

<%= render '/itinerary_users/booking_form' %>

app/views/itineraries/update.html.erb
<p>Find me in app/views/itineraries/update.html.erb</p>