config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :itineraries
    resources :itinerary_users

    root to: "users#index"
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: [:show, :edit, :update] do
    resources :itineraries, only: [:index]
  end

  resources :itineraries, only: [:new, :create, :edit, :show, :update, :destroy]
  resources :itinerary_users
  resources :searches

  root to: "searches#new"
end

app/models/search.rb
# == Schema Information
#
# Table name: searches
#
#  id             :integer          not null, primary key
#  city           :string
#  arrival_date   :datetime
#  departure_date :datetime
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Search < ActiveRecord::Base
  validates :city, :arrival_date, :departure_date, presence: true
  validate :valid_date_range?

  def itineraries
    @itineraries ||= find_itineraries
  end

private

  def find_itineraries
    itineraries = Itinerary.order(:updated_at)
    itineraries = itineraries.where("city ILIKE ?", "%#{city}%") if city.present?
    itineraries = itineraries.where(date: arrival_date .. departure_date) if dates_range_present?
    itineraries
  end

  def valid_date_range?
    errors.add(:search, "No bookings from future to past") unless dates_range_present? && arrival_date < departure_date
  end

  def dates_range_present?
    arrival_date.present? && departure_date.present?
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @search = Search.new
  end

  def create
    @search = Search.new(search_params)

    if @search.save
      respond_to do |format|
        format.html { redirect_to @search }
        format.json { render json: @search }
      end
    else
      flash[:notice] = @search.errors.full_messages.join(". ")
      render 'new'
    end

  end

  def show
    @search = Search.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search }
    end
  end

private

  def search_params
    params.require(:search).permit(:city, :arrival_date, :departure_date)
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/new.html.erb
<h1>Search for an Itinerary</h1>

<%= form_for @search do |f| %>
  <p>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </p>

  <p>
    <%= f.label :arrival_date %>
    <%= f.date_field :arrival_date %>
  </p>

  <p>
    <%= f.label :departure_date %>
    <%= f.date_field :departure_date %>
  </p>

  <p>
    <%= f.submit 'Search' %>
  </p>
<% end %>

app/views/searches/show.html.erb
<h1>Search Results</h1>

<h3>Itineraries available in <%= @search.city %> from
    <%= @search.arrival_date.strftime("%A %B %d, %Y") %> to <%= @search.departure_date.strftime("%A %B %d, %Y") %></h3>

<% @search.itineraries.each do |itinerary| %>
  <%= itinerary.name %>
  <ul>
    <li>$<%= itinerary.price %></li>
    <li><%= itinerary.spots_sold %>/<%= itinerary.total_capacity %> spots sold</li>
    <li><%= link_to "Show Details", itinerary_path(itinerary) %></li>
  </ul>
<% end %>